repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.6
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format

  - repo: https://github.com/biomejs/pre-commit
    rev: v1.9.4
    hooks:
      - id: biome-check
        additional_params: [--write]

  - repo: https://github.com/returntocorp/semgrep
    rev: v1.62.0
    hooks:
      - id: semgrep
        args: [--config, auto, --error]
